name: tests
on:
  pull_request:
    paths:
      - .github/**
      - computer-use-agent-demo/**
  push:
    branches:
      - main
    paths:
      - .github/**
      - computer-use-agent-demo/**
jobs:
  ruff:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: computer-use-agent-demo
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
  pyright:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: computer-use-agent-demo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.13.2"
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v1
  pytest:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: computer-use-agent-demo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.13.2"
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - run: pytest tests --junitxml=junit/test-results.xml
