name: tests
on:
  pull_request:
    paths:
      - .github/**
      - computer-use-demo/**
  push:
    branches:
      - main
    paths:
      - .github/**
      - computer-use-demo/**
jobs:
  ruff:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Supports both Windows and Ubuntu
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: computer-use-demo
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1

  pyright:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: computer-use-demo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.11.6"
      - run: |
          python -m venv .venv
          ${{ matrix.os == 'windows-latest' && '.venv\Scripts\activate' || 'source .venv/bin/activate' }}
          pip install -r dev-requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v1

  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: computer-use-demo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
          python-version: "3.11.6"
      - run: |
          python -m venv .venv
          ${{ matrix.os == 'windows-latest' && '.venv\Scripts\activate' || 'source .venv/bin/activate' }}
          pip install -r dev-requirements.txt
      - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - run: pytest tests --junitxml=junit/test-results.xml
